CREATE TABLE CIFTCI(
	CiftciID SERIAL,
	CiftciFname VARCHAR(20),
	CiftciLname VARCHAR(15),
	CiftciMail VARCHAR(30),
	CiftciPassword VARCHAR(20),
	PRIMARY KEY (CiftciID)
);

CREATE TABLE ULKE(
	UlkeName VARCHAR(20),
	PRIMARY KEY (UlkeName)
);

CREATE TABLE BOLGE(
	BolgeID SERIAL,
	BolgeName VARCHAR(25),
	PRIMARY KEY (BolgeID)
);

CREATE TABLE IL(
	IlID SERIAL,
	IlName VARCHAR(20),
	PRIMARY KEY (IlID)
);

CREATE TABLE ILCE(
	IlceID SERIAL,
	IlceName VARCHAR(20),
	PRIMARY KEY (IlceID)
);

CREATE TABLE URUN(
	UrunID SERIAL,
	UrunName VARCHAR(20),
	UrunKatsayi VARCHAR(20),
	PRIMARY KEY (UrunID)
);

CREATE TABLE MEYVE(
	MeyveID SERIAL,
	PRIMARY KEY (MeyveID),
	FOREIGN KEY (MeyveID) REFERENCES URUN(UrunID)
);

CREATE TABLE SEBZE(
	SebzeID SERIAL,
	PRIMARY KEY (SebzeID),
	FOREIGN KEY (SebzeID) REFERENCES URUN(UrunID)
);

CREATE TABLE TAHIL(
	TahilID SERIAL,
	PRIMARY KEY (TahilID),
	FOREIGN KEY (TahilID) REFERENCES URUN(UrunID)
);

CREATE TABLE BAKLIYAT(
	BakliyatID SERIAL,
	PRIMARY KEY (BakliyatID),
	FOREIGN KEY (BakliyatID) REFERENCES URUN(UrunID)
);

CREATE TABLE VERI(
	VeriID SERIAL,
	ToplamIlacMiktari INTEGER,
	ToplamMakineSayisi INTEGER,
	IsciSayisi INTEGER,
	Yil INTEGER NOT NULL CHECK (Yil BETWEEN 1950 AND 2020),
	PRIMARY KEY (VeriID)
);

CREATE TABLE ULKEBOLGEICERIR(
	UlkeName VARCHAR(20),
	BolgeID SERIAL,
	PRIMARY KEY (UlkeName, BolgeID),
	FOREIGN KEY (UlkeName) REFERENCES ULKE(UlkeName),
	FOREIGN KEY (BolgeID) REFERENCES BOLGE(BolgeID)
);

CREATE TABLE BOLGEILICERIR(
	BolgeID SERIAL,
	IlID SERIAL,
	PRIMARY KEY (BolgeID, IlID),
	FOREIGN KEY (BolgeID) REFERENCES BOLGE(BolgeID),
	FOREIGN KEY (IlID) REFERENCES IL(IlId)
);

CREATE TABLE BARINDIRIR(
	CiftciID SERIAL,
	IlceID SERIAL,
	PRIMARY KEY (CiftciID, IlceID),
	FOREIGN KEY (CiftciID) REFERENCES CIFTCI(CiftciID),
	FOREIGN KEY (IlceID) REFERENCES ILCE(IlceID)
);

CREATE TABLE ILILCEICERIR(
	IlID SERIAL,
	IlceID SERIAL,
	PRIMARY KEY (IlID, IlceID),
	FOREIGN KEY (IlID) REFERENCES IL(IlID),
	FOREIGN KEY (IlceID) REFERENCES ILCE(IlceID)
);

CREATE TABLE YETISIR(
	BolgeID SERIAL,
	IlceID SERIAL,
	Ton INTEGER,
	Alan INTEGER,
	Yil INTEGER NOT NULL CHECK (Yil BETWEEN 1950 AND 2020),
	PRIMARY KEY (BolgeID, IlceID),
	FOREIGN KEY (BolgeID) REFERENCES BOLGE(BolgeID),
	FOREIGN KEY (IlceID) REFERENCES ILCE(IlceID)
);

CREATE TABLE ZITLASIR(
	FirstUrunID SERIAL,
	SecondUrunID SERIAL,
	PRIMARY KEY (FirstUrunID, SecondUrunID),
	FOREIGN KEY (FirstUrunID) REFERENCES URUN(UrunID),
	FOREIGN KEY (SecondUrunID) REFERENCES URUN(UrunID)
);


CREATE TABLE BULUNDURUR(
	VeriID SERIAL,
	IlID SERIAL,
	PRIMARY KEY (VeriID, IlID),
	FOREIGN KEY (VeriID) REFERENCES VERI(VeriID),
	FOREIGN KEY (IlID) REFERENCES IL(IlId)
);


